CREATE OR REPLACE VIEW "general_insurance_quicksight_view" AS 
SELECT
  policynumber "Policy Number"
, CAST(startdate AS date) "Summary Date"
, CAST(effectivedate AS date) "Policy Effective Date"
, CAST(expirationdate AS date) "Policy Expiration Date"
, insuredcompanyname "Company"
, lobcode "Line of Business"
, lobcode "LOBCode"
, neworrenewal "New or Renewal"
, insuredindustry "Industry"
, insuredsector "Sector"
, distributionchannel "Distribution Channel"
, insuredcity "City"
, insuredstatecode "State"
, insurednumberofemployees "Number of Employees"
, insuredemployeetier "Employer Size Tier"
, insuredannualrevenue "Revenue"
, territory "Territory"
, accidentyeartotalincurredamount "Claim Amount"
, policyinforce "Policy In-force"
, expiringpolicy "Policy Expiring"
, expiringpremiumamount "Premium Expiring"
, writtenpremiumamount "Written Premium"
, writtenpolicy "Written Policy"
, earnedpremium "Earned Premium"
, agentname "Agent Name"
, producercode "Agent Code"
FROM
  syntheticgeneraldata_consume.policydata